language: java
jdk:
  - oraclejdk8

jobs:
  include:
    - stage: build
      script: ./gradlew clean build
    - stage: publish
      if: branch = master AND type = push AND fork = false
      script: ./gradlew bintrayUpload -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER